export default {
    DATETIME_FORMAT: "MM/DD/YY h:mm a",
    DATETIME_FORMAT_LONG: "dddd, MMMM DD, YYYY  h:mm a",
    TIME_FORMAT: "h:mm a",
    DATE_FORMAT_LONG: "dddd, MMMM DD, YYYY",
    DATE_FORMAT_SHORT: "YYYY.MM.DD",
    YEARMONTH_FORMAT: "MMMM YYYY",
    VIEWS__SETTINGS_SETTINGS: "Settings",
    VIEWS__SETTINGS_LOGOUT: "Logout",
    VIEWS__SETTINGS_HORIZON: "Horizon (days)",
    VIEWS__SETTINGS_CALENDARS: "Calendar .ics",
    TIME_FORMAT: "h:mm a",
    VIEWS__ACTION_FREE: [
        "Press below me to schedule something!",
        "Nothing scheduled?",
        "You have nothing planned! Congrats!",
    ],
    VIEWS__DUE_SOON: "due soon",
    VIEWS__DUE_ON_DATE: "unscheduled, due on that date",
    VIEWS__SCHEDULED: "scheduled",
    VIEWS__BROWSER: "you can filter by tags @likeso and use .* regex",
    VIEWS__ACTION: "it's ",
    VIEWS__ACTION_YOUR_SCHEDULE: "here are your tasks for ",
    VIEWS__ACTION_THE_FUTURE: "the future",
    VIEWS__ACTION_TODAY_IS: "today is ",
    VIEWS__AUTH_WELCOME: ", and welcome to cao!",
    VIEWS__AUTH_HAPPY: "We are happy that you are here;",
    VIEWS__AUTH_PLEASE: "please, ",
    VIEWS__AUTH_DATA: "What you do in cao never leaves your device.",
    VIEWS__AUTH_MALFORM_HEAD: "Malformed Workspace",
    VIEWS__AUTH_MALFORM_SUBHEAD: "Please check that the file exists and is made by cao.",
    // TODO how about end delimiter management
    VIEWS__AUTH_SELECT: "select",
    VIEWS__AUTH_CREATE: "create",
    VIEWS__AUTH_WORKSPACE: " a workspace",
    COMPONENTS__RRULEMODAL_EVERY: "every so often",
    COMPONENTS__TASK_EFFORT: ["Low Effort", "Medium Effort", "High Effort"],
    COMPONENTS__RRULEMODAL_REPEAT: "Repeat...",
    COMPONENTS__RRULEMODAL_NONE: "no repeating rule",
    COMPONENTS__EDITOR__CM_PLACEHOLDER: "Go on, capture something...",
    COMPONENTS__EDITOR__PARAGRAPH_HINT: "Tap between paragraphs to seperate into subtasks.",
    COMPONENTS__TAGBAR_EMPTY: "set some?",
    COMPONENTS__TASK__TAP_TO_SCHEDULE: "unscheduled",
    COMPONENTS__TASK__NO_START_DATE: "no start date",
    COMPONENTS__TASK__NO_DUE_DATE: "no due date",
    COMPONENTS__DATEPICKER__PICK_DT: "Date or time here!",
    COMPONENTS__DATEPICKER__PICK_TIME: "Pick a time here!",
    TOOLTIPS: {
        ACTION: "Action",
        DONE: "Done",
        RESET: "Reset",
        COMPLETE: "Complete Task",
        REPEAT: "Set Repeating",
        UNCOMPLETE: "Uncomplete Task",
        DELETE: "Delete Task",
        SCHEDULED: "Set Scheduled Date",
        START: "Set Start Date",
        DUE: "Set Due Date",
        CAPTURE: "Capture",
        BROWSE: "Browse",
        SUBMIT: "Submit",
        CANCEL: "Cancel",
        PREVIOUS_SHEET: "Previous Sheet",
        NEXT_SHEET: "Next Sheet",
        PREVIOUS_DAY: "Previous Day",
        NEXT_DAY: "Next Day",
        INCREASE_CAL: "Increase Calendar Slots",
        DECREASE_CAL: "Decrease Calendar Slots",
        TASKS_MODE: "Show Tasks Only",
        CALENDAR_MODE: "Show Tasks and Events",
        LOGOUT: "Logout",
        SETTINGS: "Settings",
    },
    DAYS_OF_WEEK_VERY_SHORT: {
        1: "M",
        2: "T",
        3: "W",
        4: "T",
        5: "F",
        6: "S",
        // sad, but matches indexing scheme of
        // js. we should probably fix eventually
        0: "S",
    },
    DAYS_OF_WEEK_SHORT: {
        1: "M",
        2: "Tu",
        3: "W",
        4: "Th",
        5: "F",
        6: "Sa",
        // sad, but matches indexing scheme of
        // js. we should probably fix eventually
        0: "Su",
    },
    GREETINGS: [
        "Hello",
        "Howdy",
        "Hi"
    ],
    TEMPORAL_GREETINGS: [
        "Good morning",
        "Good afternoon",
        "Good evening"
    ]
};

